akameco/s2s

src/handlers/__tests__/__snapshots__/plugins.test.js.snap
src/handlers/__tests__/helpers/from-plugin.js
src/handlers/__tests__/plugins.test.js
src/handlers/plugins.js

Add from option

---

src/handlers/__tests__/__snapshots__/plugins.test.js.snap
src/handlers/__tests__/fixtures/b.js
src/handlers/__tests__/plugins.test.js
src/handlers/plugins.js

Resolve input path

---

src/utils/__tests__/lock.test.js

Add lock.js test.
Improve test cov.

Add test for lock.js

---

package.json
src/handlers/__tests__/__snapshots__/templates.test.js.snap
src/handlers/__tests__/templates.test.js
src/handlers/templates.js
src/types.js

Add output option to template

---

src/handlers/__tests__/plugins.test.js
src/handlers/plugins.js
src/index.js
src/types.js

Add only option

---

src/handlers/__tests__/plugins.test.js
src/handlers/plugins.js

Support [name]

---

docs/ja/readme.md

s2s.config.jsの書き方をdocsに追加

---

package.json
src/handlers/__tests__/__snapshots__/plugins.test.js.snap
src/handlers/__tests__/__snapshots__/ts-handler.test.js.snap
src/handlers/__tests__/fixtures/hello.ts
src/handlers/__tests__/plugins.test.js
src/handlers/__tests__/ts-handler.test.js
src/handlers/ts-handler.js
yarn.lock

Close #19
related #30 
`Handler`を指定することでts出力を可能にした。
モノレポにする際に、ハンドラーをコアから分離する予定。

Support ts handler

---

packages/readme.md
packages/s2s-handler-babel-next/package.json
packages/s2s-handler-babel-next/src/__snapshots__/index.test.js.snap
packages/s2s-handler-babel-next/src/__tests__/helpers/plugin.js
packages/s2s-handler-babel-next/src/index.js
packages/s2s-handler-babel-next/src/index.test.js

Pr babel next handler

---

package.json
packages/babel-plugin-s2s-action-creater/src/index.js
packages/s2s-cli/src/__snapshots__/index.test.js.snap
packages/s2s-cli/src/handlers/plugins.js
packages/s2s-cli/src/handlers/plugins.test.js
packages/s2s-cli/src/handlers/templates.js
packages/s2s-cli/src/handlers/templates.test.js
packages/s2s-cli/src/index.js
packages/s2s-cli/src/index.test.js
packages/s2s-cli/src/utils/index.js
packages/s2s-cli/src/utils/index.test.js
packages/s2s-utils/index.js
yarn.lock

wathcerまわりのテストを追加
console.logを直接使うように変更

Testカバレッジを上げる

---

packages/babel-plugin-s2s-action-types/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-action-types/src/index.js
packages/babel-plugin-s2s-action-types/src/index.test.js
packages/flow-execa/src/__snapshots__/index.test.js.snap
packages/flow-execa/src/index.test.js
packages/flow-faker/src/__fixtures__/basic.js
packages/flow-faker/src/index.js
packages/flow-faker/src/index.test.js
packages/s2s-cli/src/handlers/plugins.test.js
packages/s2s-cli/src/index.test.js

テストカバレッジを99%

---

examples/getting-started/readme.md
packages/babel-plugin-s2s-action-creater/package.json
packages/babel-plugin-s2s-action-root/package.json
packages/babel-plugin-s2s-action-types/package.json
packages/babel-plugin-s2s-initial-state-creater/package.json
packages/babel-plugin-s2s-jest-unit-test-case/package.json
packages/babel-plugin-s2s-reducer-case-creater/package.json
packages/babel-plugin-s2s-reducer-test-case/package.json
packages/babel-plugin-s2s-state-root/package.json
packages/babel-plugin-s2s-variable-initializing/package.json
packages/flow-execa/package.json
packages/flow-faker/package.json
packages/s2s-babel-flow-types/package.json
packages/s2s-helper-get-action-obj/package.json
packages/s2s-helper-get-initial-state/package.json
packages/s2s-helper-get-reducer-case/package.json
packages/s2s-plugins-redux/package.json
packages/s2s-utils/package.json
readme.md

Fix pkg GitHub field

---

.eslintrc
examples/typescript/s2s.config.js
examples/typescript/yarn.lock
packages/readme.md
packages/s2s-cli/package.json
packages/s2s-cli/src/handlers/__snapshots__/plugins.test.js.snap
packages/s2s-cli/src/handlers/plugins.js
packages/s2s-cli/src/handlers/plugins.test.js

**What**:   
**Why**: #59 
**How**: `path.extname`を使い拡張子を判定。tsの場合は`s2s-handler-typescirpt` を使う。       
**Checklist**:
Close #59

Inclide handler

---

packages/s2s-cli/src/cli/__tests__/fixtures/cjs/s2s.config.js
packages/s2s-cli/src/cli/loadConfig.js
packages/s2s-cli/src/cli/loadConfig.test.js

**What**: loadconfigにtestの追加
**Why**: cliのinputまわりに今後改良を加えたいため
**How**: 引数を取るようにした。また、process.cwdのモックを使った。
**Checklist**:

test(loadConfig): add some test

---

.github/ISSUE_TEMPLATE.md

use yarn 1.3.2
https://github.com/akameco/s2s/issues/64#issuecomment-343434527
related #64
**What**: GitHubのテンプレートを更新        
**Why**:  yarn v1.3.2以下では動作しないため。     
**How**: N/A
**Checklist**:

docs(github): update issue template

---

packages/babel-plugin-s2s-reducer-root/readme.md
packages/babel-plugin-s2s-reducer-root/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-reducer-root/src/index.js
packages/babel-plugin-s2s-reducer-root/src/index.test.js

**What**:**Why**:
#64 を修正しました。
**How**:
babel-plugin-s2s-reducer-root に対する combineReducersModule Option の追加。
テンプレートが直書きから t.stringLiteral  に変わりました。そのため シングルクォートからダブルクォートに
snapshot を更新しました。
**Checklist**:

Combine reducer option

---

packages/babel-plugin-s2s-action-creater/src/index.js
packages/babel-plugin-s2s-jest-unit-test-case/src/index.js
packages/babel-plugin-s2s-reducer-root/src/index.js
packages/s2s-utils/__snapshots__/index.test.js.snap
packages/s2s-utils/index.js
packages/s2s-utils/index.test.js

**What**: s2s-utilsにcreateImportDeclarationを追加した。`import {hoge} from 'hoge'`の抽象。
また、テストのリファクタ。         
**Why**: 共通する処理が3パッケージに渡るためまとめた。            
**How**: stirngまたはstring[]のlocalとstringのsouceを取り、最終的に`t.importDeclaration`を実行する。 
**Checklist**:

Utils create import

---

package.json
packages/s2s-cli/package.json
packages/s2s-hook-prettier/package.json
yarn.lock

**What**: update deps
**Why**:
**How**:
**Checklist**:

chore(package): update deps

---

.flowconfig
packages/babel-plugin-s2s-action-creater/package.json
packages/babel-plugin-s2s-action-creater/src/index.js
packages/babel-plugin-s2s-action-root/package.json
packages/babel-plugin-s2s-action-root/src/index.js
packages/babel-plugin-s2s-action-types/package.json
packages/babel-plugin-s2s-action-types/src/index.js
packages/babel-plugin-s2s-initial-state-creater/package.json
packages/babel-plugin-s2s-initial-state-creater/src/index.js
packages/babel-plugin-s2s-jest-unit-test-case/src/index.js
packages/babel-plugin-s2s-reducer-case-creater/package.json
packages/babel-plugin-s2s-reducer-case-creater/src/index.js
packages/babel-plugin-s2s-reducer-root/package.json
packages/babel-plugin-s2s-reducer-root/src/index.js
packages/babel-plugin-s2s-reducer-test-case/package.json
packages/babel-plugin-s2s-reducer-test-case/src/index.js
packages/babel-plugin-s2s-state-root/package.json
packages/babel-plugin-s2s-state-root/src/index.js
packages/babel-plugin-s2s-variable-initializing/package.json
packages/babel-plugin-s2s-variable-initializing/src/index.js
packages/s2s-plugins-redux/package.json
packages/s2s-plugins-redux/src/index.js
types/index.js

**What**:
flowの参照をlibからsrcに変更。これで再ビルドの必要がなくなった
また、それぞれのパッケージからs2s-babel-flow-typesへの依存をなくした。
全ての型は`type`を参照する。
**Why**: flowの型がlibを参照しているので混乱する。     
**How**: typeに集約     
**Checklist**:

refactor(type): udpate type

---

docs/en/config.md
docs/ja/config.md
packages/s2s-cli/src/handlers/plugins.js
packages/s2s-handler-babel-next/src/index.js
packages/s2s-handler-babel-next/src/index.test.js
packages/s2s-handler-babel/src/index.js
packages/s2s-handler-babel/src/index.test.js
packages/s2s-handler-typescript/src/index.js
packages/s2s-handler-typescript/src/index.test.js
types/index.js

**What**: Pluginをオプショナルにした。それに伴い、それぞれのハンドラーを修正。
**Why**: 任意のハンドラーを適用可能にしたから。
**How**: 
**Checklist**:

Pr update type

---

packages/babel-plugin-s2s-initial-state-creater/__fixtures__/array-exist.js
packages/babel-plugin-s2s-initial-state-creater/__fixtures__/array.js
packages/babel-plugin-s2s-initial-state-creater/__fixtures__/number.js
packages/babel-plugin-s2s-initial-state-creater/__fixtures__/string-exist.js
packages/babel-plugin-s2s-initial-state-creater/__fixtures__/string.js
packages/babel-plugin-s2s-initial-state-creater/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-initial-state-creater/src/index.js
packages/babel-plugin-s2s-initial-state-creater/src/index.test.js

**What**: Stateが配列及びプリミティブ型のときも初期化可能にした
**Why**:  #73
**How**: Flowの型と実装の型が異なるとき、Flowの型の初期化値で上書き
**Checklist**:
Closes #73

feat(initial-state-creater): support array or primitive

---

packages/babel-plugin-s2s-initial-state-creater/__fixtures__/string-exist.js
packages/babel-plugin-s2s-initial-state-creater/src/__snapshots__/index.test.js.snap

**What**:
**Why**:
**How**:
**Checklist**:

test: fix flowfixme

---

package.json
scripts/publish.sh

**What**: 
**Why**: publishの前にbuildとtestとlintを実行したい
**How**: scripts/publish.shの追加
**Checklist**:

chore(package): add publish script

---

packages/babel-plugin-s2s-func-param-init/__fixtures__/index.js
packages/babel-plugin-s2s-func-param-init/package.json
packages/babel-plugin-s2s-func-param-init/readme.md
packages/babel-plugin-s2s-func-param-init/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-func-param-init/src/index.js
packages/babel-plugin-s2s-func-param-init/src/index.test.js

**What**: 関数のパラメータがオブジェクトで型付けされているとき、自動生成をする。
**Why**: Reactのpropsを高速で記述可能
**How**: はじめの引数がidentifierのとき、型情報によってオブジェクトを取得し、設定
**Checklist**:
Closes #82

feat(plugin-function-param-init): add new babel plugin

---

flow-typed/npm/jest_v21.x.x.js
package.json
packages/s2s-handler-babel-next/package.json
packages/s2s-handler-typescript/package.json
yarn.lock

**What**: ライブラリのバージョンとflow-typedの型を更新       
**Why**:
**How**:
**Checklist**:

ライブラリ及びflow-typedの更新

---

types/index.js

**What**:
**Why**: 型を明確に
**How**:
**Checklist**:

chore(type): tweak

---

readme.md

**What**:
**Why**: getting statedの手段をミスっていた
**How**:
**Checklist**:

docs(readme): fix readme

---

packages/babel-plugin-s2s-jest-unit-test-case/src/index.js
packages/babel-plugin-s2s-reducer-case-creater/src/index.js
packages/s2s-helper-get-action-obj/src/index.js
packages/s2s-helper-get-initial-state/src/index.js
packages/s2s-helper-get-reducer-case/src/index.js

**What**: コメントタイプを普通の型付けに変更
**Why**: パッケージ内で統一
**How**:
**Checklist**:

refactor(flow): remove flow comments type

---

package.json

**What**:
**Why**:
**How**:
**Checklist**:

chore(script): not fmt after install

---

packages/babel-plugin-s2s-reducer-case-creater/package.json
packages/babel-plugin-s2s-reducer-case-creater/src/__fixtures__/sameParam.js
packages/babel-plugin-s2s-reducer-case-creater/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-reducer-case-creater/src/index.js
packages/babel-plugin-s2s-reducer-case-creater/src/index.test.js
packages/s2s-helper-get-action-obj/src/index.js
packages/s2s-helper-get-action-obj/src/index.test.js

**What**: case文追加時にアクションのパラメータを追加
**Why**: プロパティがある場合更新するとわかっている場合が多い
**How**: helperを追加
```js
// actionTypes.js
export type Set = {
type: typeof SET,
count: number,
}
export type Action = Set
// reducer.js
export default function(state: State = initialState, action) {
switch (action.type) {
default:
return state
}
}
↓ ↓ ↓ ↓ ↓ ↓
export default function (state: State = initialState, action) {
switch (action.type) {
case Actions.SET:
return {
...state,
count: action.count
};
default:
return state;
}
}
```
**Checklist**:

feat(reducer-case-creater): create object with action type

---

appveyor.yml
packages/babel-plugin-s2s-action-types/package.json
packages/babel-plugin-s2s-action-types/src/index.js
packages/flow-execa/src/index.js
packages/flow-execa/src/index.test.js
packages/s2s-cli/src/templates/index.js
packages/s2s-cli/src/utils/index.js
packages/s2s-utils/src/index.js
packages/s2s-utils/src/index.test.js

**What**: appveyorの追加
**Why**: windows対応をするため
**How**: 
**Checklist**:

fix(windows): fix windows env

---

packages/flow-execa/src/index.js
packages/flow-execa/src/index.test.js

**What**: windowsのflowのbinのパスを修正
**Why**: windows対応のため
**How**: platformの判別をやめた
**Checklist**:

fix(windows): fix flow path

---

package.json

**What**:`'`を`\"`に変更
**Why**: windows環境で`yarn fmt`が落ちる
**How**: `'`を`\"`に変更
**Checklist**:

chore(npm): fix fmt script with using \" #91

---

.prettierignore
docs/ja/readme.md
readme.md

**What**: サンプルのリンクを追加     
**Why**:
**How**:
**Checklist**:

docs(readme): add example

---

packages/babel-plugin-s2s-action-root/package.json
packages/babel-plugin-s2s-action-root/src/index.js
packages/s2s-utils/package.json
packages/s2s-utils/src/index.js
yarn.lock

**What**:
**Why**: windows対応
**How**: 入力をノーマライズ      
**Checklist**:

fix(action-root): use normalizePathSeq

---

packages/flow-execa/src/index.test.js
packages/flow-faker/src/index.test.js
packages/s2s-cli/package.json
packages/s2s-cli/src/utils/index.js

**What**:
**Why**: windows対応
```
● getOutputPath when output = relative path
expect(received).toBe(expected)
Expected value to be (using ===):
"/src/actions.js"
Received:
"C:/src/actions.js"
at Object.<anonymous>.test (packages/s2s-cli/src/utils/index.test.js:42:18)
```
**How**:  ノーマライズ     
**Checklist**:

fix(windows): normalize-path-sep

---

packages/s2s-handler-babel-next/package.json
packages/s2s-handler-babel-next/src/index.js
packages/s2s-handler-babel/package.json
packages/s2s-handler-babel/src/__tests__/helpers/plugin.js
packages/s2s-handler-babel/src/index.js
packages/s2s-handler-babel/src/index.test.js
packages/s2s-handler-typescript/package.json
packages/s2s-handler-typescript/src/index.js
packages/s2s-helper-get-plugin-name/package.json
packages/s2s-helper-get-plugin-name/src/index.js
packages/s2s-helper-get-plugin-name/src/index.test.js

**What**:
**Why**:   プラグインが関数の場合でもプラグイン名を表示させるため         
**How**: get-plugin-name関数を作成し、新しいパッケージとした          
**Checklist**:

feat(handler): add s2s-helper-get-plugin-name

---

packages/s2s-cli/src/handlers/index.js
packages/s2s-cli/src/handlers/index.test.js

**What**: ENOENTのとき、エラーメッセージを短く
**Why**: #105
**How**: 
**Checklist**:
Closes #105

fix(s2s-cli): short error message

---

packages/s2s-cli/src/handlers/__snapshots__/handle-plugin.test.js.snap
packages/s2s-cli/src/handlers/__snapshots__/index.test.js.snap
packages/s2s-cli/src/handlers/__tests__/fixtures/a.test.js
packages/s2s-cli/src/handlers/handle-plugin.js
packages/s2s-cli/src/handlers/handle-plugin.test.js
packages/s2s-cli/src/handlers/index.js
packages/s2s-cli/src/handlers/index.test.js
packages/s2s-cli/src/handlers/select-handler.js
packages/s2s-cli/src/handlers/select-handler.test.js

**What**:
**Why**: テストが読みづらいため、ファイルを分割。
**How**:
**Checklist**:

refactor(s2s): update handlers

---

CONTRIBUTING.md

**What**:
- CONTRIBUTING.mdの表記を修正
- typo修正
- yarn 使う流れだったので、npmからyarnにしてみました
**Why**:
**How**:
**Checklist**:

fix(document): `add-contributor` scripts in CONTRIBUTING.md

---

docs/en/config.md
docs/ja/config.md
packages/s2s-hook-tslint/README.md
packages/s2s-hook-tslint/__fixtures__/basic/actual.ts
packages/s2s-hook-tslint/__fixtures__/basic/expected.ts
packages/s2s-hook-tslint/__fixtures__/basic/tslint.json
packages/s2s-hook-tslint/package.json
packages/s2s-hook-tslint/src/index.js
packages/s2s-hook-tslint/src/index.test.js
yarn.lock

**What**:
- ref #113
- tslintのhookを追加
- プラグインの開発に関連した箇所のドキュメントを追加
**Why**:
- 生成コードとlint設定に矛盾が存在する場合しんどい
**How**:
- linting
- fixした後の文字列を取得する方法が分からなかったので、fixした後にfs.readFileSyncを呼び出し
- testing
- `__fixtures__` のサブディレクトリの `actual.ts` を `tmp.ts` に複製後、それにlint実行
- tslint.jsonは各サブディレクトリ参照
**Checklist**:
flowも英語も初心者なので、色々よろしくお願いします :bow:

add new packages `s2s-hook-tslint`

---

examples/shopping-cart/src/containers/CartContainer/actionTypes.js
examples/shopping-cart/src/containers/CartContainer/actions.js
examples/shopping-cart/src/containers/CartContainer/reducer.js
examples/shopping-cart/src/containers/ProductsContainer/actionTypes.js
packages/babel-plugin-s2s-action-types/readme.md
packages/babel-plugin-s2s-action-types/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-action-types/src/index.js

**What**:  `action-types`の順序の入れ替え。また、サンプルの更新。
**Why**: 型の位置を一番上に変更
**How**:  `programPath.node.body`の順序を入れ替え
**Checklist**:
refs: #118

feat(s2s-action-types): change order

---

examples/shopping-cart/flow-typed/global.js
examples/shopping-cart/src/containers/CartContainer/reducer.js
examples/shopping-cart/src/containers/CartContainer/reducer.test.js

**What**:   flow && reducer
**Why**:  #121 
**How**: flowの修正およびreducerの追加
**Checklist**:
Closes #121

chore(examples/shopping-cart): fix shopping cart error

---

packages/s2s-cli/src/handlers/handle-plugin.js
packages/s2s-cli/src/handlers/handle-plugin.test.js
packages/s2s-cli/src/hooks/index.js

- passed to hook from inputPath to outputPath.
**What**:
- #123
- 試しに変更してみました
**Why**:
**How**:
**Checklist**:

[s2s-cli] change hook api.

---

.prettierignore
examples/getting-started/package.json
examples/shopping-cart/package.json
flow-typed/slash.js
jest.config.js
package.json
packages/babel-plugin-s2s-action-creater/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-action-root/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-action-types/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-func-param-init/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-initial-state-creater/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-jest-unit-test-case/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-reducer-case-creater/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-reducer-root/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-reducer-test-case/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-state-root/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-variable-initializing/src/__snapshots__/index.test.js.snap
packages/s2s-cli/package.json
packages/s2s-cli/src/handlers/index.test.js
packages/s2s-cli/src/hooks/index.test.js
packages/s2s-cli/src/index.test.js
packages/s2s-cli/src/templates/index.test.js
packages/s2s-handler-babel-next/package.json
packages/s2s-handler-typescript/package.json
packages/s2s-utils/src/__snapshots__/index.test.js.snap
yarn.lock

**What**: 依存の更新
**Why**: パッケージを最新に保つため
**How**: 
**Checklist**:
Jest22へのアップデートによりスナップショットの差分がたくさん出た

依存の更新: Jest22へのアップデート

---

packages/readme.md
packages/s2s-handler-css-to-flow/package.json
packages/s2s-handler-css-to-flow/readmd.md
packages/s2s-handler-css-to-flow/src/__snapshots__/index.test.js.snap
packages/s2s-handler-css-to-flow/src/index.js
packages/s2s-handler-css-to-flow/src/index.test.js
yarn.lock

**What**:  cssからflowの型定義を生成するハンドラーの追加。React CSS Modulesを使っている時に型チェックができる
**Why**:  js以外のハンドラーを追加したかった
**How**:  `css-to-flow`を呼び出す。`css-to-flow`の内部では`postcss`のパーサを呼び出している。
**Checklist**:

feat(s2s-handler-css-to-flow): add s2s-handler-css-to-flow

---

examples/shopping-cart/src/containers/CartContainer/actionTypes.js
examples/shopping-cart/src/containers/ProductsContainer/actionTypes.js
packages/babel-plugin-s2s-action-types/readme.md
packages/babel-plugin-s2s-action-types/src/__snapshots__/index.test.js.snap
packages/babel-plugin-s2s-action-types/src/index.js
yarn.lock

This reverts commit c5538a3971b929195277fb9a19e56af879c01783.
**What**: `ActionType.js`において型定義を一番うしろに書く。
**Why**:  コードを追加する際にファイルの一番後ろに書くのは合理的
**How**: 変更をrevert
**Checklist**:

revert(s2s-action-types): "feat(s2s-action-types): change order (#119)"

---

packages/s2s-cli/src/utils/index.test.js

**What**:  カバレッジの向上。
**Why**:  コードの品質を保つため
**How**:  s2s-cliにテストの追加
**Checklist**:

test(s2s-cli): imporove coverage

---

docs/en/config.md
docs/ja/config.md
examples/getting-started/s2s.config.js
examples/shopping-cart/s2s.config.js
packages/s2s-cli/src/index.js

**What**: watchにデフォルトの値を設定
**Why**:  適切なデフォルトにより管理するコードを減らすため。
**How**: watchに`./**/*.js`をデフォルトとして設定。
**Checklist**:

feat(s2s-cli): set default value watch='./**/*.js

---

examples/import-css/.flowconfig
examples/import-css/package.json
examples/import-css/s2s.config.js
examples/import-css/src/index.js
examples/import-css/src/styles.css
examples/import-css/src/styles.css.flow
packages/s2s-handler-css-to-flow/src/__snapshots__/index.test.js.snap
packages/s2s-handler-css-to-flow/src/index.js
packages/s2s-handler-css-to-flow/src/index.test.js

**What**:  handlerからデフォルトの設定をexportまた、css-to-flowのサンプルを追加
**Why**:  適切なデフォルトは環境構築を楽にする
**How**:  設定はsnapshotテストをした。
**Checklist**:

feat(handler): add default config

---

examples/getting-started/s2s.config.js
examples/shopping-cart/flow-typed/global.js
examples/shopping-cart/s2s.config.js
packages/babel-plugin-s2s-variable-initializing/src/index.js
packages/s2s-plugins-redux/src/index.js
scripts/build.js

**What**: デフォルトの設定をexportした
**Why**: デフォルトの設定をexportすることでconfigの設定を容易にする
**How**:  その他。それにともなう修正
**Checklist**:

feat(plugin): use default conig

---

package.json

**What**:  lintをコミット時に走らせることから除外
**Why**: 時間がかかり開発速度を落とす
**How**: 
**Checklist**:

ci(lint): run lint only ci

---

CONTRIBUTING.md
package.json
scripts/build.js
scripts/getPackages.js
scripts/watch.js

**What**:  watchスクリプトの追加。npmスクリプトの変更。
**Why**:  高速な開発イテレーションのため。
**How**:  jestのscript/watchを利用。
**Checklist**: 
多段表示が、s2sのcliより便利なので還元しようか迷う。

build: add watch script

---

package.json

**What**:  lint-stagedの使い方を間違えていた。
**Why**:  本来のlint-stagedの使い方に修正。
**How**:  just `prettier --write`
**Checklist**:

chore(lint-staged): fix target

---

.eslintignore
jest.config.js

**What**: templatesがignoreされていたので修正
**Why**: 
**How**: 
**Checklist**:

chore(*): fix ignore path

---

.prettierignore
docs/ja/config.md
examples/shopping-cart/s2s.config.js
packages/s2s-cli/package.json
packages/s2s-cli/src/templates/__snapshots__/index.test.js.snap
packages/s2s-cli/src/templates/__tests__/fixtures/copy-result.js
packages/s2s-cli/src/templates/__tests__/fixtures/copy.js
packages/s2s-cli/src/templates/index.js
packages/s2s-cli/src/templates/index.test.js
packages/s2s-templates-redux/templates/components.js
packages/s2s-templates-redux/templates/containers.js
yarn.lock

**What**:  s2s-cliのtemplate展開時、FILENAME,DIRNAMEを使う事ができる。また、テンプレート内でコードを書いておけば展開時に実行される。
**Why**:  ファイルの作成のコストを減らすため。例えば、reactのコンポーネント名を自動的に記述が可能である。
**How**:  copyのロジックをそのまま`ejs.render`に変更
**Checklist**:

feat(s2s-cli): ejs support

---

package.json
packages/babel-plugin-s2s-initial-state-creater/package.json
yarn.lock

**What**: 
**Why**: 
**How**: 
**Checklist**:

chore(npm): update packages

---

readme.md

**What**: readmeの目次の追加 
**Why**:  
**How**: `npx doctoc  --maxlevel 3 --notitle readme.md`
**Checklist**:

chore(readme): use doctoc

---

packages/s2s-handler-babel-next/src/__snapshots__/index.test.js.snap
packages/s2s-handler-babel-next/src/index.js
packages/s2s-handler-babel-next/src/index.test.js
packages/s2s-handler-babel/src/__snapshots__/index.test.js.snap
packages/s2s-handler-babel/src/index.js
packages/s2s-handler-babel/src/index.test.js

**What**:  babylonに適切なデフォルトオプションを追加する。
**Why**:  痛みなく多くのプラグインを使うことができる。
**How**: parserOptsの追加
**Checklist**:

feat(handler): set default parser option

---

examples/react-class-to-sfc/package.json
examples/react-class-to-sfc/readme.md
examples/react-class-to-sfc/s2s.config.js
examples/react-class-to-sfc/src/index.js
yarn.lock

**What**:  サンプルの追加
**Why**: 
**How**: 
**Checklist**:

chore(exmaple): add react-class-to-sfc

---

.eslintignore
examples/shopping-cart/.eslintrc.json
examples/shopping-cart/src/api/shop.js
examples/shopping-cart/src/components/Cart/index.js
examples/shopping-cart/src/components/Cart/index.test.js
examples/shopping-cart/src/components/Product/index.test.js
examples/shopping-cart/src/components/ProductItem/index.js
examples/shopping-cart/src/components/ProductItem/index.test.js
examples/shopping-cart/src/components/ProductList/index.test.js
examples/shopping-cart/src/containers/CartContainer/index.js
examples/shopping-cart/src/containers/CartContainer/reducer.js
examples/shopping-cart/src/containers/ProductById/reducer.test.js
examples/shopping-cart/src/containers/ProductsContainer/index.js
examples/shopping-cart/src/containers/ProductsContainer/selectors.test.js
examples/shopping-cart/src/registerServiceWorker.js
examples/shopping-cart/src/types/index.js

**What**:  exampleディレクトリにeslintの適用
**Why**: 
**How**: 
**Checklist**:

chore(eslint): use eslint in examples

---

.all-contributorsrc
packages/s2s-cli/src/index.js
readme.md

**What**: 
s2sのtemplate機能でディレクトリの変更も検知するようにしました。
**Why**: 
Re-ducksなどのフォルダ構成において、親ディレクトリを作るとその中身が作られるプラグインを作りたかったため。
**How**: 
watcherの監視するイベントに`'addDir'`イベントを追加
**Checklist**:

feat(template) add 'addDir' watch event.
